[config]
skip_core_tasks = true

[tasks.clean]
script = '''
'''

[tasks.run]
script = '''
swift run
'''

[tasks.format]
script = '''
swiftformat .
'''

[tasks.lint]
dependencies = ["format"]
script = '''
swiftlint
'''

[tasks.build]
dependencies = ["lint"]
script = '''
swift build
'''

[tasks.test]
dependencies = ["lint"]
script = '''
swift test 2>&1 | xcbeautify
'''
